/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function mapping___getClassname(a: number, b: number): void;
export function __wbg_mapping_free(a: number): void;
export function mapping_new(a: number, b: number, c: number, d: number, e: number, f: number): number;
export function mapping_generated_line(a: number): number;
export function mapping_generated_column(a: number): number;
export function mapping_original_line(a: number, b: number): void;
export function mapping_original_column(a: number, b: number): void;
export function mapping_source(a: number, b: number): void;
export function mapping_source_index(a: number, b: number): void;
export function mapping_set_source(a: number, b: number, c: number): void;
export function mapping_set_source_index(a: number, b: number, c: number): void;
export function mapping_name(a: number, b: number): void;
export function mapping_set_name(a: number, b: number, c: number): void;
export function mapping_set_name_index(a: number, b: number, c: number): void;
export function mapping_compare_by_generated_positions_inflated(a: number, b: number): number;
export function mapping_compareByGeneratedPositionsDeflated(a: number, b: number): number;
export function __wbg_generator_free(a: number): void;
export function generator_new(a: number, b: number, c: number): number;
export function generator_addMapping(a: number, b: number, c: number, d: number): void;
export function generator_applyMapping(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function generator_getMappings(a: number): number;
export function generator_set_source_content(a: number, b: number, c: number): void;
export function generator_toJSON(a: number): number;
export function generator_toString(a: number, b: number): void;
export function parseMappings(a: number, b: number, c: number): void;
export function __wbindgen_malloc(a: number): number;
export function __wbindgen_realloc(a: number, b: number, c: number): number;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_free(a: number, b: number): void;
export function __wbindgen_exn_store(a: number): void;
