name: Lint
on: [ push, pull_request_target ]

jobs:
    build:
        runs-on: ubuntu-latest
        name: Node 18 - on Linux
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: 18
            - run: npm install
            - run: npm install -g eslint
            - run: eslint src/
