name: Tests - Linux
on: [ push, pull_request_target ]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version:
                    - 10
                    - 12
                    - 14
                    - 15
                    - 16
                    - 17
                    - 18
                    - 19

        name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on Linux

        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node_version }}
                  architecture: ${{ matrix.architecture }}
            - run: npm install
            - run: npm test
